config_file = "kohya/toml/asamu.toml"
pretrained_model_name_or_path = "deepghs/animefull-latest"
v2 = false
train_data_dir = ""
prior_loss_weight = 1
resolution = "768,1024"
enable_bucket = true
min_bucket_reso = 768
max_bucket_reso = 1_600
bucket_reso_steps = 64
output_name = ""
output_dir = ""
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 1
max_train_epochs = 8
train_batch_size = 2
gradient_checkpointing = false
network_train_unet_only = false
network_train_text_encoder_only = false
learning_rate = 1
unet_lr = 1
text_encoder_lr = 1
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "Prodigy"
network_module = "networks.lora"
network_dim = 16
network_alpha = 8
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
max_token_length = 255
multires_noise_iterations = 6
multires_noise_discount = 0.3
seed = 1_337
clip_skip = 2
mixed_precision = "bf16"
full_bf16 = true
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false
persistent_data_loader_workers = true
optimizer_args = [
  "decouple=True",
  "weight_decay=0.01",
  "use_bias_correction=True",
  "d_coef=2.0"
]
