config_file = "kohya/toml/default_char.toml"
pretrained_model_name_or_path = "deepghs/animefull-latest"
v2 = false
train_data_dir = ""
prior_loss_weight = 1
resolution = "512,768"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 4096
bucket_reso_steps = 64
output_name = ""
output_dir = ""
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 2
max_train_epochs = 10
train_batch_size = 1
gradient_checkpointing = false
network_train_unet_only = false
network_train_text_encoder_only = false
learning_rate = 1
unet_lr = 1
text_encoder_lr = 1
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "Prodigy"
network_module = "networks.lora"
network_dim = 32
network_alpha = 32
network_dropout = 0
scale_weight_norms = 0
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
weighted_captions = false
keep_tokens = 1
max_token_length = 255
caption_tag_dropout_rate = 0.2
noise_offset = 0.5
seed = 1337
clip_skip = 2
mixed_precision = "fp16"
full_fp16 = false
full_bf16 = false
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = false
cache_text_encoder_outputs_to_disk = false
persistent_data_loader_workers = true
optimizer_args = [ "decouple=True", "weight_decay=0.01", "use_bias_correction=True", "d_coef=2.0",]
